// Generated by CoffeeScript 1.6.3
(function() {
  define(['jquery', 'sha1', 'codebird', 'typeahead'], function($) {
    'use strict';
    var getVerse;
    if (!String.linkify) {
      String.prototype.linkify = function() {
        var emailAddressPattern, pseudoUrlPattern, urlPattern;
        urlPattern = /\(?\bhttp:\/\/[-A-Za-z0-9+&@#\/%?=~_()|!:,.;]*[-A-Za-z0-9+&@#\/%=~_()|]/g;
        pseudoUrlPattern = /(^|[^\/])(www\.[\S]+(\b|$))/g;
        emailAddressPattern = /\w+@[a-zA-Z_]+?(?:\.[a-zA-Z]{2,6})+/g;
        return this.replace(urlPattern, "<a href=\"$&\">$&</a>").replace(pseudoUrlPattern, "$1<a href=\"http://$2\">$2</a>").replace(emailAddressPattern, "<a href=\"mailto:$&\">$&</a>");
      };
    }
    getVerse = function() {
      var cb;
      console.log("Getting verse.");
      cb = new Codebird;
      cb.setConsumerKey("Ruh48JJwUvtX5znpgHISVg", "4FH1GrYQBZvp9ajsOjXeuxWyIvD5IApIEBnphOaJJ08");
      cb.__call("oauth2_token", {}, function(reply) {
        var bearer_token;
        return bearer_token = reply.access_token;
      });
      return cb.__call("statuses_userTimeline", {
        screen_name: "Daily_Bible",
        count: 1
      }, function(reply) {
        var d;
        $("#verse").html(reply[0]['text'].linkify());
        if (typeof Storage !== "undefined") {
          d = new Date();
          localStorage.date = d.getDate() + 1;
          return localStorage.verse = reply[0]['text'];
        }
      }, true);
    };
    return $(document).ready(function() {
      var today;
      $.fn.center = function() {
        return this.css("margin-left", -($(this).outerWidth() / 2));
      };
      $(window).resize(function() {
        return $(".hero").center();
      });
      $(".hero").center();
      $('input[name="q"]').typeahead([
        {
          name: "Google",
          remote: {
            url: "http://google.com/complete/search?output=firefox&q=%QUERY",
            dataType: "jsonp",
            filter: function(parsedResponse) {
              return parsedResponse[1];
            }
          }
        }
      ]).focus();
      if (typeof Storage && localStorage.date) {
        today = new Date().getDate();
        if (localStorage.date < today) {
          localStorage.removeItem("verse");
        }
        if (localStorage.verse) {
          console.log("Using localStorage verse");
          return $("#verse").html(localStorage.verse.linkify());
        } else {
          return getVerse();
        }
      } else {
        return getVerse();
      }
    });
  });

}).call(this);
